---
title: "HW 18" 
author: "Harsha"
date: "2024-03-19"
output: 
   html_document:
     code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#global rules for entire markdown
```

#### Part 1

```{r fig.height=3, fig.width=3}
library(ggplot2)

# Load and prep the data
set.seed(23)
a  <- round(runif(10, 5, 15))
df <- data.frame( a )

#Doing the manual way 
a.o <- sort(a)
i     <- 1 : length(a)          # Create indices
f.val <- (i - 0.5) / length(a)  # Compute the f-value
a.fi  <- data.frame(a.o, f.val) # Create dataframe of sorted values


#Both on same graph 
ggplot() +
  geom_point(data=a.fi, aes(x = f.val, y = a.o),  size = 3, color= "red") + 
  xlab("fval") + ylab("a") +
  aes(sample = df$a) + 
  stat_qq(distribution = qunif, size=2)


```

#### Part 2

```{r fig.height=3, fig.width=3}

#Method 4
f.val.4 <- (i) / length(a)  # Compute the f-value
a.fi.4  <- data.frame(a.o, f.val.4) # Create dataframe of sorted values

#Plot both on same graph to see if are same 
ggplot() +
geom_point(data=a.fi.4, aes(x = f.val.4, y = a.o),  size = 3, color= "red") + 
xlab("fval") + ylab("a") +
aes(sample = df$a) + 
stat_qq(distribution = qunif, size=2) #not same

#Method 6
f.val.6 <- (i) / (length(a)+1)  # Compute the f-value
a.fi.6  <- data.frame(a.o, f.val.6) # Create dataframe of sorted values

#Plot both on same graph to see if are same 
ggplot() +
geom_point(data=a.fi.6, aes(x = f.val.6, y = a.o),  size = 3, color= "red") + 
xlab("fval") + ylab("a") +
aes(sample = df$a) + 
stat_qq(distribution = qunif, size=2) #not same

#Method 7
f.val.7 <- (i-1) / (length(a)-1)  # Compute the f-value
a.fi.7  <- data.frame(a.o, f.val.7) # Create dataframe of sorted values

#Plot both on same graph to see if are same 
ggplot() +
geom_point(data=a.fi.7, aes(x = f.val.7, y = a.o),  size = 3, color= "red") + 
xlab("fval") + ylab("a") +
aes(sample = df$a) + 
stat_qq(distribution = qunif, size=2) #not same

#Method 8
f.val.8 <- ( i-(1/3) / (length(a) + (1/3) ) ) # Compute the f-value
a.fi.8 <- data.frame(a.o, f.val.8) # Create dataframe of sorted values

#Plot both on same graph to see if are same 
ggplot() +
geom_point(data=a.fi.8, aes(x = f.val.8, y = a.o),  size = 3, color= "red") + 
xlab("fval") + ylab("a") +
aes(sample = df$a) + 
stat_qq(distribution = qunif, size=2) #not same

#Method 9
f.val.9 <- (i-3/8) / (length(a)+.25)  # Compute the f-value
a.fi.9 <- data.frame(a.o, f.val.9) # Create dataframe of sorted values

#Plot both on same graph to see if are same 
ggplot() +
geom_point(data=a.fi.9, aes(x = f.val.9, y = a.o),  size = 3, color= "red") + 
xlab("fval") + ylab("a") +
aes(sample = df$a) + 
stat_qq(distribution = qunif, size=2) #same

```

Stat_qq uses method 9, which is $$
fvalue_i = \frac{i -3/8}{n+1/4} 
$$

Here, n is the length of the data or vector in question. Lower case is the index of a particular data point. 
